# Generated by Django 3.1 on 2021-02-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username_slug',
            field=models.SlugField(default='hello', editable=False, help_text='The unique slug that will be used to identify the user', max_length=100),
            preserve_default=False,
        ),
    ]
