# Generated by Django 3.1.7 on 2021-03-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_username_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vault_password',
            field=models.CharField(blank=True, help_text="The password that can be used to access the user's secret vault.Should be stored as a hashed pasword.", max_length=150, null=True),
        ),
    ]
