query getHabitDetails($nameSlug: String!) {
  getHabitDetails(nameSlug: $nameSlug) {
    habit {
      name
      startedOn
      duration
      progress
      description
      isDone
      isCompleted
    }
    error
  }
}
