# Generated by Django 3.1.6 on 2021-02-06 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyHabit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the particular habit you are trying to cultivate.', max_length=200)),
                ('started_on', models.DateTimeField(auto_now_add=True, help_text='The date and time this particular habit was started.')),
                ('duration', models.DurationField(help_text='The number of {0}s you plan to continue this habit for.')),
                ('progress', models.JSONField(blank=True, help_text='The progress of the habit being tracked. Each {0} (corresponding to duration) has a truth value whether that the habit was followed that {0} or not.', null=True)),
                ('user', models.ForeignKey(help_text='The user that wants to cultivate this particular habit.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyHabit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the particular habit you are trying to cultivate.', max_length=200)),
                ('started_on', models.DateTimeField(auto_now_add=True, help_text='The date and time this particular habit was started.')),
                ('duration', models.DurationField(help_text='The number of {0}s you plan to continue this habit for.')),
                ('progress', models.JSONField(blank=True, help_text='The progress of the habit being tracked. Each {0} (corresponding to duration) has a truth value whether that the habit was followed that {0} or not.', null=True)),
                ('user', models.ForeignKey(help_text='The user that wants to cultivate this particular habit.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='hourlyhabit',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_habit_name_for_hourlyhabit'),
        ),
        migrations.AddConstraint(
            model_name='dailyhabit',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_habit_name_for_dailyhabit'),
        ),
    ]
