# Generated by Django 3.1 on 2021-02-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyhabit',
            name='name_slug',
            field=models.SlugField(default='ok', editable=False, help_text='The unique slug that will be used to identify the habit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hourlyhabit',
            name='name_slug',
            field=models.SlugField(default='pl', editable=False, help_text='The unique slug that will be used to identify the habit', max_length=100),
            preserve_default=False,
        ),
    ]
