# Generated by Django 3.1 on 2021-02-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_auto_20210224_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyhabit',
            name='started_on',
            field=models.DateField(auto_now_add=True, help_text='The date and time this particular habit was started.'),
        ),
        migrations.AlterField(
            model_name='hourlyhabit',
            name='started_on',
            field=models.DateField(auto_now_add=True, help_text='The date and time this particular habit was started.'),
        ),
    ]
