# Generated by Django 3.1 on 2021-02-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_auto_20210226_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyhabit',
            name='description',
            field=models.TextField(default='hello description', help_text='A brief description of what the habit is going to be about'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hourlyhabit',
            name='description',
            field=models.TextField(default='this description', help_text='A brief description of what the habit is going to be about'),
            preserve_default=False,
        ),
    ]
