# Generated by Django 3.1 on 2021-02-27 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_auto_20210226_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyhabit',
            options={'ordering': ('-date_from',)},
        ),
        migrations.RemoveField(
            model_name='dailyhabit',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='dailyhabit',
            name='started_on',
        ),
        migrations.AddField(
            model_name='dailyhabit',
            name='date_from',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date this particular habit was started.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyhabit',
            name='date_to',
            field=models.DateField(default=django.utils.timezone.now, help_text='The date this particular habit is supposed to be completed.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyhabit',
            name='progress',
            field=models.JSONField(blank=True, help_text='The progress of the habit being tracked. Each `date` (corresponding to duration) has a truth value whether that the habit was followed that day or not.', null=True),
        ),
        migrations.DeleteModel(
            name='HourlyHabit',
        ),
    ]
