# Generated by Django 3.1 on 2021-02-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_auto_20210227_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyhabit',
            name='date_from',
            field=models.DateField(help_text='The date this particular habit was started.'),
        ),
    ]
