# Generated by Django 3.1.7 on 2021-03-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_auto_20210227_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyhabit',
            name='vault',
            field=models.BooleanField(default=False, help_text='Whether the habit will be stored in the vault, that is, not appear in the normal habit lists.'),
        ),
    ]
